"""Classical tomography baseline helpers."""

from tomobench.tomography.corpus import (
    KnownRayCorpusInversionOutputs,
    KnownRayPerturbationCorpusInversionOutputs,
    run_known_ray_corpus_inversion,
    run_known_ray_perturbation_corpus_inversion,
)
from tomobench.tomography.comparison import (
    FinalPhase6ComparisonOutputs,
    compute_ml_cell_centered_case_metrics,
    node_centered_values_to_cell_centered,
    run_final_phase6_comparison,
)
from tomobench.tomography.inversion import (
    CoverageAwareKnownRayInversionOutputs,
    KnownRayInversionOutputs,
    KnownRayPerturbationInversionOutputs,
    cell_centered_velocity_target,
    cell_coverage_diagnostics,
    run_known_ray_inversion_diagnostic,
    run_known_ray_perturbation_inversion_diagnostic,
    run_coverage_aware_known_ray_inversion_diagnostic,
    solve_damped_least_squares_slowness,
    solve_prior_perturbation_slowness,
    solve_smoothed_damped_least_squares_slowness,
    smoothing_difference_matrix,
    smoothing_normal_matrix,
    summarize_cell_coverage,
)
from tomobench.tomography.sensitivity import (
    RayPathSensitivityValidationResult,
    build_ray_path_sensitivity_records,
    load_sensitivity_records_jsonl,
    load_travel_time_ray_paths_jsonl,
    ray_path_cell_lengths,
    save_ray_path_sensitivity_sidecar,
    validate_sensitivity_sidecar_files,
    validate_sensitivity_path_lengths,
)
from tomobench.tomography.reference import (
    ReferenceRayCorpusInversionOutputs,
    build_layered_reference_velocity_grid,
    run_reference_ray_corpus_inversion,
    run_reference_ray_case_inversion,
    solve_reference_ray_perturbation_slowness,
)

__all__ = [
    "KnownRayInversionOutputs",
    "CoverageAwareKnownRayInversionOutputs",
    "FinalPhase6ComparisonOutputs",
    "KnownRayCorpusInversionOutputs",
    "KnownRayPerturbationCorpusInversionOutputs",
    "KnownRayPerturbationInversionOutputs",
    "ReferenceRayCorpusInversionOutputs",
    "RayPathSensitivityValidationResult",
    "build_ray_path_sensitivity_records",
    "build_layered_reference_velocity_grid",
    "cell_centered_velocity_target",
    "cell_coverage_diagnostics",
    "compute_ml_cell_centered_case_metrics",
    "load_sensitivity_records_jsonl",
    "load_travel_time_ray_paths_jsonl",
    "node_centered_values_to_cell_centered",
    "ray_path_cell_lengths",
    "run_coverage_aware_known_ray_inversion_diagnostic",
    "run_final_phase6_comparison",
    "run_known_ray_corpus_inversion",
    "run_known_ray_inversion_diagnostic",
    "run_known_ray_perturbation_corpus_inversion",
    "run_known_ray_perturbation_inversion_diagnostic",
    "run_reference_ray_case_inversion",
    "run_reference_ray_corpus_inversion",
    "save_ray_path_sensitivity_sidecar",
    "solve_damped_least_squares_slowness",
    "solve_prior_perturbation_slowness",
    "solve_smoothed_damped_least_squares_slowness",
    "solve_reference_ray_perturbation_slowness",
    "smoothing_difference_matrix",
    "smoothing_normal_matrix",
    "summarize_cell_coverage",
    "validate_sensitivity_sidecar_files",
    "validate_sensitivity_path_lengths",
]
